version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops_web_network

networks:
  devops_web_network:
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/devops/portainer_data"
