version: "3.0"

services:
  nginx:
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: home_proxy_conf
        target: /etc/nginx/conf.d/home.conf
    volumes:
      - type: bind
        source: /opt/devops/web_folder
        target: /usr/share/nginx/html
    networks:
      - devops_network
    deploy:
      mode: replicated
      replicas: 1

configs:
  nginx_conf:
    file: ./nginx/conf/nginx.conf
  home_proxy_conf:
    file: ./nginx/conf/conf.d/home.conf

networks:
  devops_network:
    driver: overlay
    attachable: true
